### ISSUE TITLE
xkeysnail --watch cause random key no respond issue

### ISSUE THREAD

**Issue by zw963** [mooz/xkeysnail#103]
Hi, i meet this issue recent days since i reinstall a new refresh arch linux (GNOME3 + Wayland)

At the beginning, i suspect if this is a issue caused by my keyboard, system, or the
way start xkeysnail. (.config/autostart/xkeysnail.desktop).

But, finally, i found this issue caused by xkeysnail, because when i kill xkeysnail, 
the no respond key is start to works again.

In fact, i am not sure if this issue always happen, because no respond key is random,
if that key is a rarely used key, i could not find out anyway.

And,  occasionally, even all input key is no respond, (But Ctrl+C, or Ctrl+Alt+F3 still working),
after i open a login session, and kill xkeysnail, start to works again, i guess this case caused
by some prefix key(e.g. CTRL) is keeping pressed status.

If you need more debug detail, please tell me how to. thank you.

**Comment by joshgoebel** [comment]
Is this still an issue on 0.4.0?

**Comment by zw963** [comment]
Sorry, long time not use this package anymore, it possible was fixed anyway. 

thank you.
