### ISSUE TITLE
How to unbind Alt?

### ISSUE THREAD

**Issue by Gieted** [mooz/xkeysnail#124]
I'm trying to make it so Alt presses are ignored, is it possible?

**Comment by EskoJTH** [comment]
In my experience some programs capture the alt key despite of what you have in xkeysnail. The solution that I have used is to individually disable alt on every program where it is a problem. I believe you can't do this in for example electron and as such I have just elected not to use any electron apps.

But I hope I'm wrong with this and there is a way to turn it off in electron and I hope this could have a better implementation to begin with to skip the alt problem. But that is all I know.

**Comment by Gieted** [comment]
I've found a nice solution.

Simply replace Left Control and Left Alt in Gnome Tweaks.
Then nothing will happen upon pressing Alt, because Control usually does nothing on itself.
