### ISSUE TITLE
Just to confirm: some "weird" mappings, they aren't possible?

### ISSUE THREAD

**Issue by for-coursera** [mooz/xkeysnail#159]
Mappings like **modifiers only** to something (e.g., RAlt-LAlt to RSuper-Space), I can't define such combos, right? Or **several keys without modifiers** to something (e.g., Caps-F1 to Shift-F1), I can't do this, too?

My understanding is that it's not possible, but just wanted to confirm to know this for sure :)

Sorry for possible misunderstandings.

**Comment by joshgoebel** [comment]
Nope, but with multipurpose modmaps you could use caps lock by assigning it to one of the ACTUAL modifiers, that's actually oneo f the examples in the example config.py:

```
# Capslock is escape when pressed and released. Control when held down.
# {Key.CAPSLOCK: [Key.ESC, Key.LEFT_CTRL]
```

**Comment by for-coursera** [comment]
Thanks, Josh!
