### ISSUE TITLE
Thanks for your work, can't wait for xkeysnail

### ISSUE THREAD

**Issue by samrayleung** [mooz/xkeysnail#2]
Mr. mooz , I just open an new issue to say thanks for your work and can't wait for xkeysnail, I am a big fan of the tools you build, including `percol`,`js2-mode`,and `keysnail`.I am here to express my appreciation and how excited I am :)

**Comment by ellakk** [comment]
Yeah, just found it today by a note in the old keysnail repository. It's working great!

**Comment by mooz** [comment]
Thanks for the encouraging words!
