### ISSUE TITLE
Compatibility wiht at-home-modifier

### ISSUE THREAD

**Issue by jumper047** [mooz/xkeysnail#29]
Hi, last years i can't use emacs-style key bindings without this - https://gitlab.com/at-home-modifier/at-home-modifier-evdev/wikis/home
With this utility my "space" sends Ctrl keycode when pressed with another key (so, space+b == ctrl+b for example). But seems like this is not working with keysnail. It seeing space+b as space and b, not like ctrl-b. Is it possible to fix it, or add similiar functionality to xkeysnail?

**Comment by ellakk** [comment]
Use the multipurpose feature, check the example config for an example. In your case i think it would be:
```python
define_multipurpose_modmap(
    # Space is Space when pressed and released. Control when held down.
    {Key.SPACE: [Key.SPACE, Key.LEFT_CTRL]
)
```

**Comment by jumper047** [comment]
New achievement unlocked - RTFM!:)
Thank you!
