### ISSUE TITLE
Firefox captures alt before xkeysnail

### ISSUE THREAD

**Issue by EskoJTH** [mooz/xkeysnail#43]
When trying to get emacs like key bindings in firefox the alt key is captured by firefox before xkeysnail. What follows is that every time you try to give (M-_) command the Firefox opens up some sort of file options menu and commands are lost in that.

Users should be informed this will happen because with this I can't really use xkeysnail  for the main thing I wanted it for. I have run into this issue before with autohotkey on windows for example but I thought it might work under linux.

**Comment by singletS** [comment]
Try toggling Firefox's about:config options  `ui.key.menuAccessKeyFocuses` and maybe `accessibility.accesskeycausesactivation` to False.  I think the first option is the one that actually disables the Alt menu activation problem you mentioned.

**Comment by EskoJTH** [comment]
Ha! Now it works! Thank you very much! I Didn't know Firefox had access to that level of settings.
Only thing I had to  change was ui.key.menuAccessKeyFocuses to false

**Comment by phil-s** [comment]
Perhaps I've misunderstood the concept, but hasn't something already gone awry if Firefox is *able* to grab a keypress before xkeysnail?  Couldn't there then be any number of similar exceptions?

**Comment by thiagoa** [comment]
I'm having this same problem with Slack. Does anyone know how to make Alt shortcuts work with Slack? It captures the alt key before xkeysnail and focuses on the menu.

**Comment by EskoJTH** [comment]
If I'm not mistaken Slack is an electron app and it so it is basically a chrome browser. If you figure out how to do that for chrome you may be able to find the same settings inside slack. I'm mainly using firefox directly for similar applications myself but it would be nice to know how to make those work.

**Comment by WJCFerguson** [comment]
Edit: ignore this, it seems to work now.  Perhaps some restart made it work

----

Has something changed with Firefox since the earlier comments?  Setting `ui.key.menuAccessKeyFocuses` and `accessibility.accesskeycausesactivation` to `false` doesn't allow Alt keys to work for me.

(I'm a new user, so haven't seen it work)

Firefox 87.0, Ubuntu 20.04, Gnome Shell 3.36, Xorg (non-Wayland)

**Comment by EskoJTH** [comment]
> Has something changed with Firefox since the earlier comments? Setting `ui.key.menuAccessKeyFocuses` and `accessibility.accesskeycausesactivation` to `false` doesn't allow Alt keys to work for me.
> 
> (I'm a new user, so haven't seen it work)
> 
> Firefox 87.0, Ubuntu 20.04, Gnome Shell 3.36.

Works fine on Firefox 87.0, Ubuntu 20.04 wayland(I didin't know this was even supposed to work on that), and on xmonad on to of ubuntu on xorg. I didin't manage to open xorg ubuntu with gnome as I seem to have too many configurations on top.
All I have is ```ui.key.menuAccessKeyFocuses``` on ```false```. Have you checked that it works outside of firefox?

**Comment by MinmoTech** [comment]
Sorry for the off-topic comment.

Is Firefox running on xwayland?
I'd be curious if xkeysnail completely works on gnome wayland already

**Comment by WJCFerguson** [comment]
I am using Xorg, not Wayland, but now for some reason it works.  I don't know what changed, but perhaps a full Firefox restart?  I thought I restarted, but I use two Firefox profiles and probably only restarted them one at a time, if that could make a difference.  Whatever it is, my alt keys are working now in Firefox and elsewhere.  Sorry for any false alarm.

Love that it now works - very happy to have basic Emacs keys everywhere...

**Comment by EskoJTH** [comment]
> Sorry for the off-topic comment.
> 
> Is Firefox running on xwayland?
> I'd be curious if xkeysnail completely works on gnome wayland already

Seems to work on at least the wayland I got with ubuntu 20.04. I haven't used this at all, just accidentally tested on wayland and everything seems to have worked perfectly so far. I can do painting and kill text and key combinations also.

**Comment by WJCFerguson** [comment]
Huh, I was puzzled about mine fixing itself but convinced myself it must have been something to do with logging out and back in.  But now mine has seemingly spontaneously stopped translating Firefox Alt keys again.  I can't think what has changed.  Firefox didn't update, `about:config` options still set.  Of course I've restarted xkeysnail, logged out and in, and rebooted.

It must be something about my setup, since nobody else is  complaining, but I can't think what.
