### ISSUE TITLE
Mapping SUPER/HYPER

### ISSUE THREAD

**Issue by p-kolacz** [mooz/xkeysnail#53]
I need to remap my second spacebar, which is recognized as MENU key to HYPER (or SUPER). In xmodmap I use `keycode 135 = Hyper_R`. Since xmodmap doesn't work with xkeysnail, is it possible to do this in `define_modmap`?

**Comment by Lenbok** [comment]
Did you try it?

**Comment by p-kolacz** [comment]
I did try load xmodmap on system start and it was reset by xkeysnail, but now I tried to run it AFTER xkeysnail and it works. Thanks:) And thanks for this cool tool, now I have Emacs mapping everywhere:)

**Comment by Lenbok** [comment]
I meant did you try to create an equivalent `define_modmap` mapping with xkeysnail :-).

I use `conditional_modmap` and `conditional_multipurpose_modmap` to make my (dumb fallback) MS Natural keyboard behave more like my QMK mech keyboard via:

```
# The next global modmap and multipurpose modmap are just when
# using non QMK keyboards, in my case Microsoft Natural.
# [Global modemap] Change modifier keys as in xmodmap
define_conditional_modmap(lambda wm_class, device_name: device_name.startswith("Microsoft"), {
   Key.RIGHT_ALT: Key.RIGHT_CTRL
})

# [Multipurpose modmap] Give a key two meanings. A normal key when pressed and
# released, and a modifier key when held down with another key.
define_conditional_multipurpose_modmap(lambda wm_class, device_name: device_name.startswith("Microsoft"), {
   # Capslock is tab when pressed and released.
   # Control when held down.
   Key.CAPSLOCK: [Key.TAB, Key.LEFT_CTRL],

   # Tab is grave when pressed and released.
   # Win/Super when held down.
   Key.TAB: [Key.GRAVE, Key.LEFT_META],

   # Left shift is open paren when pressed and released.
   # Left shift when held down.
   Key.LEFT_SHIFT: [Key.KPLEFTPAREN, Key.LEFT_SHIFT],

   # Right shift is close paren when pressed and released.
   # Right shift when held down.
   Key.RIGHT_SHIFT: [Key.KPRIGHTPAREN, Key.RIGHT_SHIFT]
})

```

**Comment by DanielHouston** [comment]
@Lenbok Sorry to hijack this topic; but does is `conditional_multipurpose_modmap` a type of modmap? I don't see it defined anywhere!

**Comment by Lenbok** [comment]
@DanielHouston See #52, and since it's currently not merged you will need to checkout the pr in order to run it.
