### ISSUE TITLE
How to exchange Right_Shift and Left_Brace?

### ISSUE THREAD

**Issue by senlinmuvs** [mooz/xkeysnail#65]
Not working like this:
```
define_modmap({
    Key.RIGHT_SHIFT: Key.LEFT_BRACE
})
```

**Comment by Lenbok** [comment]
Did you try it with RIGHT_SHIFT spelt correctly?

**Comment by senlinmuvs** [comment]
> Did you try it with RIGHT_SHIFT spelt correctly?

Sorry, it's still the same, it can't listen to the press of a single shift key at all.

**Comment by QiangF** [comment]
Maybe try this:

    define_multipurpose_modmap({
        Key.RIGHT_SHIFT: [Key.CAPSLOCK, Key.RIGHT_CTRL], 
    })

I can bind single press of shift to delete with no problem.

**Comment by senlinmuvs** [comment]
Thank you, in fact, I want to achieve such a demand: 
[+ H: left
[+ J: down
[+ K: up
[+ L: right

But this doesn't work:
```
define_modmap({
    Key.RIGHT_SHIFT: Key.LEFT_BRACE, 
})
define_keymap(None, {
    K("RShift-h"): K("LEFT"),
    K("RShift-j"): K("DOWN"),
    K("RShift-k"): K("UP"),
    K("RShift-l"): K("RIGHT"),
    K("RShift-d"): K("DELETE"),
}, "quick move")
```
Is there a way?

**Comment by senlinmuvs** [comment]
Thank you. Now I can:
[+H:left
[+J:down
[+K:up
[+L:right
good tools!
