### ISSUE TITLE
Ways to bound C-g to set_mark(False) only

### ISSUE THREAD

**Issue by haji-ali** [mooz/xkeysnail#67]
First of all, let me express my absolute gratitude for this package. I have been looking for something like this for the longest time and your package is absolutely amazing.

I am using the default configuration and I noticed that `C-g` is  bound to `esc` followed by `set_mark(False)`. This works as intended in most cases. However, in some cases this has undesirable effects. For example, in Firefox when editing the location bar if I select some text using `C-SPC` then press `C-g` to unset the mark, `esc` is pressed which cancels all editing.

I would like to bound `C-g` to `set_mark(False)` if a mark is set and `esc` otherwise. Or, if not possible, maybe bound `C-g` to `set_mark(False)` and `C-g C-g` to `esc`. Would that be doable?

**Comment by Lenbok** [comment]
In your config, before where you define the keymap containing `c-g`, put something like this:

```
def clear_mark_or(combo):
    if isinstance(combo, Key):
        combo = Combo(None, combo)

    def _clear_mark_or():
        if transform._mark_set:
            transform._mark_set = False
        else:
            return combo

    return _clear_mark_or
```

Now in the keymap define `c-g` like this:

```
    K("C-g"): clear_mark_or(K("esc")),
```

It seems to work as your first request (although like M-w, the selection is still visible until you subsequently move).

**Comment by haji-ali** [comment]
Brilliant!!

I changed your code to return `K("right")` when the mark is set. This becomes almost identical to Emacs behaviour, except for the fact that the cursor is always to the right of the selection even when the point should be to the left. I would have to somehow return `K("left")` when the "mark" is to the right of the "point" and `K("right")` otherwise, but I am not sure how to accomplish this.

This is also related to another thing that I wish I could change. In Emacs when `C-SPC` is pressed on an active selection, the previous selection is undone and the "mark" is at the "point". This would be easy to accomplish if I could figure out where the "point" is by sending the appropriate "left" or "right" keys.

**Comment by joshgoebel** [comment]
What is this "selection" or "point" that you're referring to?  All we know is what keys you hit - _we know nothing about what you're editing, what is selected, where your cursor is or isn't at..._  so it's impossible to make decision based on such info.
