### ISSUE TITLE
Breaking changes of mod key release in xkeysnail 0.3.0

### ISSUE THREAD

**Issue by ncaq** [mooz/xkeysnail#74]
Breaking changes in xkeysnail 0.3.0.

The behavior is very different when you operate the keyboard in the following order.

~~~~
press Ctrl
press Alt
release Ctrl
press W
~~~~

xkeysnail 0.2.0: perform `Alt-w`
xkeysnail 0.3.0: perform `w`

This behavior is especially problematic when you are operating Emacs.
I perform `C-SPC` → `C-e` → `M-w`.
When performing an operation such as, I have to be careful not to release the Ctrl key before hitting the Alt key but `w` will be typed.

I think this breaking change because
[Release mapped modifiers after the original is released. closes #70. by rbreaves - Pull Request #71 - mooz/xkeysnail](https://github.com/mooz/xkeysnail/pull/71)
I'm not sure why this change was necessary in the first place when I look at the issue.

I'd like to ask @rbreaves what his intentions were in making the change to fix the disruptive change while maintaining the significance of the change.

---

original strings

xkeysnail 0.3.0の破壊的変更について.

以下の順にキーボードを操作したとき動作が大きく異なります.

~~~
press Ctrl
press Alt
release Ctrl
press w
~~~

xkeysnail 0.2.0: perform `Alt-w`
xkeysnail 0.3.0: perform `w`

この動作は特にEmacsを操作している時に問題になります.
`C-SPC` → `C-e` → `M-w`
のような操作をした時に,
Altキーを押す前にCtrlキーを離さないように慎重に気をつけないと`w`が入力されてしまいます.

私はこの破壊的変更が
[Release mapped modifiers after the original is released. Closes #70. by rbreaves · Pull Request #71 · mooz/xkeysnail](https://github.com/mooz/xkeysnail/pull/71)
によって引き起こされたと思っていますが,
そもそもこの変更が何故必要だったのかissueを見てもよく分かりませんでした.

この変更の意義を保ったまま破壊的変更を修正するために @rbreaves に変更の意図を聞きたいです.

**Comment by rbreaves** [comment]
I’ll take a look at what needs to be changed to fix it. I submitted the change so that Alt-Tab & Ctrl-Tab shortcuts could be properly remapped.

The prior behavior of quickly emitting hotkeys instead of mimicking the actual modifier release is fine in many cases but not for hotkeys that need a held key as it’s the held key that will keep Window switching active (Alt-tab). Ctrl-tab is more specific to the app, but without a held modifier in some apps the tab switching will break if most recently used is the default behavior, you’ll only switch between 2 tabs instead of the entire list of tabs.

**Comment by rbreaves** [comment]
Can you share w/ me your emacs config.py shortcuts file so I can make sure I know that I’ve resolved it?

**Comment by ncaq** [comment]
@rbreaves 
My xkeysnail config is [ncaq/.xkeysnail: My xkeysnail config](https://github.com/ncaq/.xkeysnail).
But I do not apply special setting xkeysnail for Emacs.
xkeysnail drop modifier for all application.

**Comment by rbreaves** [comment]
Ok, thank you @ncaq . I will try and work through this tomorrow or some time this week. I will either fix it in the K( ) function or propose a new one such as HK( ) for held key and honestly I thought about doing that, but given my specific needs and use cases I hadn't tested it as thoroughly as I'd have liked.

Perhaps we can come up with some sort of unit tests or another to verify that new features or features I write don't break existing functionality lol.

**Comment by rbreaves** [comment]
And that is interesting @ncaq, I will use xbindkeys -mk to monitor the difference then and see what I need to change to have things passing through the same as it does under 0.2.

**Comment by rbreaves** [comment]
So I guess I shouldn't have admitted guilt so quickly @ncaq lol. It appears the breakage occurred by @kevinslashslash. I am not saying my own changes may not need to be modified slightly, but the issue existed before my own commit.

```
git diff 56df0b9..8c4fadb
```

commit 8c4fadbd96e81e2527100347099779f36c22afba
Author: Kevin Barry <kevin@teslacoilsw.com>
Date:   Sat Mar 23 02:16:29 2019 -0500

    Fix modifier pressed/released handling
    
    Previous send_combo would release/press modifiers unnecessarily
    and sometimes trigger double-tap actions in apps.
    This was likely introduced when handling of independent handling of
    left/right modifiers was introduced.
    Now modifiers are conservatively pressed/released.

commit 56df0b9312a4345f593ba19d7497c7450f0e3303
Author: Masafumi Oyamada <stillpedant@gmail.com>
Date:   Sun Jan 13 14:59:16 2019 +0900

    Extract device operations into methods

**Comment by rbreaves** [comment]
Going through it some more I have discovered an actual bug that I did introduce but I am working on getting the logic changed right now on the shift key so that the issue will go away. I wouldn't mind fixing the other behavioral issue as well, but it is less severe than the shift key issue I introduced which could cause it to become stuck on any remap that involves the shift key on the destination..

**Comment by rbreaves** [comment]
Despite not having introduced the bug/behavior I have submitted a new commit/PR that I believe resolves the issues @ncaq.

**Comment by ncaq** [comment]
I'm sorry.
I run `git blame` result is

```
d79a3bc086a6635ffc3c8f8ef41c646b6f563407 is the first bad commit
commit d79a3bc086a6635ffc3c8f8ef41c646b6f563407
Author: Ben Reaves <rbreaves@gmail.com>
Date:   Sat Apr 18 19:37:50 2020 -0500
    Added release mapped modifiers only when original modifier has been released
 xkeysnail/output.py    | 13 ++++++++-----
 xkeysnail/transform.py |  8 +++++++-
 2 files changed, 15 insertions(+), 6 deletions(-)
```

So I miss find the commit.

**Comment by rbreaves** [comment]
Interesting, I have never seen or used git bisect before.. seems I am still learning new things about git all the time 😅. I tend to just use gitk or the git diff tool when I am inspecting things and it was fine to call me out earlier. @Lenbok had certainly found some issues with nested key remaps that needed fixing before the last merge.

**Comment by yoshinari-nomura** [comment]
In my case, after e3dcedd, i.e. merging PR #71, `escape_next_key` doesn't work well.

With this simple configuration:
```
import re
from xkeysnail.transform import *

define_keymap(None, {
    # Escape
    K("C-q"): escape_next_key,
}, "Test")
```

`C-qC-p` no longer passes `C-p` to the application (`p` is passed instead).
You have to release all keys after `C-q` and then press `C-p` to pass `C-p`.

git bisect reports that first bad commit: [6cf21fe816e0bf696abb1ba5dd270cc05350f029] 
> Updated release modifier fix to unset mode_maps properly

Unfortunately, PR #76 does not solve my problem.

**Comment by yoshinari-nomura** [comment]
I noticed that when I pushed down the `C-qC-p` sequence very quickly, it worked as expected.
It seems that some kind of timeout process may not be working well.

**Comment by shicks** [comment]
Is anyone looking into this anymore?  At this point I've reverted to 0.2.0 to avoid it, but it would be nice to get updates.

**Comment by joshgoebel** [comment]
@ncaq Just to be clear here your issue here wasn't with any type of remapping, but just with the basic pass-thru behavior breaking your keystroke chains, yes?  I'm trying to understand all the issues here to see if we can have our cake and eat it also - have a release that handles both cases without requiring any custom patches.

**Comment by ncaq** [comment]
@joshgoebel 
I'm not too sure I understand the question properly.
Yes, the problem was that the combination with Ctrl and Alt was broken.
