### ISSUE TITLE
Install instruction for ubuntu

### ISSUE THREAD

**Issue by vascotenner** [mooz/xkeysnail#77]
Installing from pip requires python3-dev to be installed. Please change readme.md  to:
```sudo apt install python3 python3-pip python3-dev```

**Comment by rbreaves** [comment]
python3-dev or python3-devel is only required if you will be compiling it yourself, but I had included your suggestion in my existing pull request for updating the readme to also include a case insensitivity example.

Additionally, I imagine python3 will install as a dependency along with python3-pip, so I left it out.

**Comment by vascotenner** [comment]
Thank you for including this.
